/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AsyncView: typeof import('./src/components/view/AsyncView.vue')['default']
    AsyncViewItem: typeof import('./src/components/view/AsyncViewItem.vue')['default']
    AsyncViewItemComponents: typeof import('@arco-design/web-vue')['Input']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    SyncView: typeof import('./src/components/view/SyncView.vue')['default']
    SyncViewItem: typeof import('./src/components/view/SyncViewItem.vue')['default']
    SyncViewItemComponents: typeof import('@arco-design/web-vue')['Input']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
