/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AViewAsync: typeof import('./src/components/AView/AViewAsync.vue')['default']
    AViewSync: typeof import('./src/components/AView/AViewSync.vue')['default']
    BarComponent: typeof import('./src/components/dummy/BarComponent.vue')['default']
    BazComponent: typeof import('./src/components/dummy/BazComponent.vue')['default']
    BViewAsync: typeof import('./src/components/BView/BViewAsync.vue')['default']
    BViewSync: typeof import('./src/components/BView/BViewSync.vue')['default']
    copy: typeof import('./src/components/viewA/DuplicateName copy.vue')['default']
    CViewAsync: typeof import('./src/components/CView/CViewAsync.vue')['default']
    CViewSync: typeof import('./src/components/CView/CViewSync.vue')['default']
    DuplicateName: typeof import('./src/components/viewC/DuplicateName.vue')['default']
    DuplicateNameAsync: typeof import('./src/components/viewA/DuplicateNameAsync.vue')['default']
    DuplicateNameSync: typeof import('./src/components/viewA/DuplicateNameSync.vue')['default']
    FooComponent: typeof import('./src/components/dummy/FooComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NormalName: typeof import('./src/components/viewC/NormalName.vue')['default']
    NormalNameAsync: typeof import('./src/components/viewA/NormalNameAsync.vue')['default']
    NormanNameAsync: typeof import('./src/components/viewA/NormanNameAsync.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
